env:
  - GO111MODULE=on
builds:
  - main: cmd/gcrgc/gcrgc.go
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - "386"
      - amd64
release:
  prerelease: auto
changelog:
  filters:
    exclude:
      - '^Merge pull request'
