language: go

go:
  - "1.11"
  - "1.12"
  - "1.13"
  - "1.14"
  - tip

matrix:
  # It's ok if our code fails on unstable development versions of Go.
  allow_failures:
    - go: tip
  # Don't wait for tip tests to finish. Mark the test run green if the
  # tests pass on the stable versions of Go.
  fast_finish: true

# Don't email me the results of the test runs.
notifications:
  email: false

# Skip the install step. Don't `go get` dependencies. Only build with the
# code in vendor/
install: true

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  - go vet ./...

# push results to CodeCov
after_success:
  - bash <(curl -s https://codecov.io/bash)
